In [25]:
import pandas as pd
testds = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\mnist_test.csv.xls")
trainds = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\mnist_train.csv.xls")

In [26]:
trainds

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0          5    0    0    0    0    0    0    0    0    0  ...      0      0   
1          0    0    0    0    0    0    0    0    0    0  ...      0      0   
2          4    0    0    0    0    0    0    0    0    0  ...      0      0   
3          1    0    0    0    0    0    0    0    0    0  ...      0      0   
4          9    0    0    0    0    0    0    0    0    0  ...      0      0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
59995      8    0    0    0    0    0    0    0    0    0  ...      0      0   
59996      3    0    0    0    0    0    0    0    0    0  ...      0      0   
59997      5    0    0    0    0    0    0    0    0    0  ...      0      0   
59998      6    0    0    0    0    0    0    0    0    0  ...      0      0   
59999      8    0    0    0    0    0    0    0    0    0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
59995      0      0      0      0      0      0      0      0  
59996      0      0      0      0      0      0      0      0  
59997      0      0      0      0      0      0      0      0  
59998      0      0      0      0      0      0      0      0  
59999      0      0      0      0      0      0      0      0  

[60000 rows x 785 columns]

In [27]:
import numpy as np
train=np.array(trainds)

In [28]:
test1=np.array(testds.loc[:,testds.columns!='label'])
test2=np.array(testds['label'])

In [29]:
testds 

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0         7    0    0    0    0    0    0    0    0    0  ...      0      0   
1         2    0    0    0    0    0    0    0    0    0  ...      0      0   
2         1    0    0    0    0    0    0    0    0    0  ...      0      0   
3         0    0    0    0    0    0    0    0    0    0  ...      0      0   
4         4    0    0    0    0    0    0    0    0    0  ...      0      0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
9995      2    0    0    0    0    0    0    0    0    0  ...      0      0   
9996      3    0    0    0    0    0    0    0    0    0  ...      0      0   
9997      4    0    0    0    0    0    0    0    0    0  ...      0      0   
9998      5    0    0    0    0    0    0    0    0    0  ...      0      0   
9999      6    0    0    0    0    0    0    0    0    0  ...      0      0   

      28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0         0      0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...    ...  
9995      0      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0      0  
9999      0      0      0      0      0      0      0      0  

[10000 rows x 785 columns]

In [30]:
import numpy as np

classs=[]
for i in range (10):
    classs.append(train[train[:,0] == 1])
classs

[array([[1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0

In [31]:
classs1=[]
for i in range (10):
    classs1.append(train[train[:,0] == 1])
classs1[0]

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [32]:
import random
value1=[]
for i in range (10):
    for j in range(5):
        value1.append(np.array(random.sample(list(classs1[i]),int(len(classs1[i])//5))))
        classs1[i]=classs[i]
value1

[array([[1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0

In [33]:
mean={}
for i in range(len(classs)):
    mean[f'{i}']=np.mean(value1[i][:,1:],axis=0)
mean

{'0': array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.0

In [34]:
mean={}
for i in range(50):
    mean[f'{i}']=np.mean(value1[i][:,1:],axis=0)
mean

{'0': array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.0

In [35]:
one = []
for i in range(10):
    for j in range(5):
        one.append(i)
np.array(one)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8,
       8, 9, 9, 9, 9, 9])

In [36]:

a = []
for i in range(10000):
    
    dist = []
    index = 0
    X = []
    for j in range(10):
        for k in range(5):
            dist.append(np.linalg.norm(test1[i] - mean[f'{index}']))
            index += 1
    dist = np.array(dist)
    dist = np.stack((dist,one),axis = 1)
    dist = dist.astype("int64")
    dist = dist[dist[:,0].argsort()]
    X = dist[:5]
    X
    var = 0
    
    for j in range(5):
        for n in X[:,1]:
            if np.count_nonzero(X[:,1]== n) > 1:
                var = n
            else:
                var = n
    a.append(n)

In [37]:
print(a)

[6, 1, 1, 8, 3, 0, 8, 1, 0, 3, 6, 7, 1, 1, 0, 4, 6, 4, 0, 3, 6, 0, 6, 8, 4, 5, 4, 3, 1, 7, 1, 6, 6, 4, 7, 3, 6, 6, 2, 1, 0, 5, 1, 5, 9, 0, 6, 4, 7, 4, 2, 6, 1, 4, 7, 1, 3, 2, 0, 1, 7, 3, 6, 7, 7, 4, 7, 3, 1, 4, 4, 6, 7, 3, 0, 6, 4, 4, 0, 5, 4, 4, 7, 4, 3, 7, 9, 6, 2, 1, 1, 8, 4, 4, 6, 1, 4, 6, 2, 6, 4, 3, 1, 3, 4, 3, 3, 7, 1, 2, 4, 6, 1, 9, 4, 4, 3, 3, 6, 3, 9, 6, 4, 1, 1, 4, 7, 1, 5, 4, 2, 7, 9, 1, 7, 9, 1, 7, 7, 8, 4, 4, 4, 5, 7, 5, 9, 4, 7, 1, 9, 4, 4, 0, 6, 6, 4, 1, 8, 6, 3, 4, 3, 3, 3, 2, 3, 7, 7, 4, 3, 3, 7, 4, 2, 0, 4, 5, 6, 2, 6, 9, 6, 4, 7, 8, 3, 7, 6, 4, 2, 4, 1, 7, 4, 8, 6, 3, 3, 5, 1, 1, 9, 7, 5, 5, 6, 6, 5, 2, 4, 9, 7, 4, 1, 2, 3, 0, 8, 1, 8, 1, 1, 2, 9, 4, 1, 2, 7, 8, 1, 1, 1, 5, 5, 4, 4, 2, 1, 7, 4, 7, 5, 6, 4, 2, 7, 0, 3, 7, 6, 2, 1, 1, 7, 6, 6, 9, 7, 7, 6, 6, 4, 4, 1, 6, 5, 0, 7, 0, 6, 1, 7, 4, 6, 3, 0, 1, 7, 4, 7, 1, 0, 4, 4, 3, 2, 3, 4, 1, 5, 5, 9, 4, 3, 2, 4, 0, 7, 7, 6, 6, 7, 3, 3, 1, 7, 4, 5, 0, 1, 6, 4, 7, 6, 1, 3, 5, 1, 3, 7, 8, 0, 5, 1, 6, 5, 8, 5, 6, 6, 9, 6, 

In [38]:

count=0
for i in range(10000):
    if a[i]==test2[i]:
        count+=1
count

715

In [39]:
Tacc= count/len(test2)*100
print("Total accuracy: ",Tacc)

Total accuracy:  7.1499999999999995


In [40]:
compare=np.stack((a,test2),axis = 1)
compare

array([[6, 7],
       [1, 2],
       [1, 1],
       ...,
       [5, 4],
       [9, 5],
       [8, 6]], dtype=int64)

In [41]:
count=[]
for i in range(len(compare)):
    if compare[i,0] != compare[i,1]:
        count.append(test2[i])
    
len(count)


9285

In [42]:
for i in set(a):
    countds=list(test2).count(i)
    freq=count.count(i)
    print(f'Accuracy for class{i}:',100-freq/countds*100 )

Accuracy for class0: 9.08163265306122
Accuracy for class1: 11.629955947136565
Accuracy for class2: 7.8488372093023315
Accuracy for class3: 6.831683168316829
Accuracy for class4: 15.987780040733199
Accuracy for class5: 3.0269058295964157
Accuracy for class6: 2.7139874739039698
Accuracy for class7: 7.10116731517509
Accuracy for class8: 1.026694045174537
Accuracy for class9: 5.054509415262629
