In [1]:
import pandas as pd
import numpy as np
import random 

In [2]:
df1=pd.read_csv("D:\Data_Analytaics\Sem-3\Basics of ML(DC-302)\Data\mnist_train.csv")
df2=pd.read_csv("D:\Data_Analytaics\Sem-3\Basics of ML(DC-302)\Data\mnist_test.csv")

In [3]:
df1

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0          5    0    0    0    0    0    0    0    0    0  ...      0      0   
1          0    0    0    0    0    0    0    0    0    0  ...      0      0   
2          4    0    0    0    0    0    0    0    0    0  ...      0      0   
3          1    0    0    0    0    0    0    0    0    0  ...      0      0   
4          9    0    0    0    0    0    0    0    0    0  ...      0      0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
59995      8    0    0    0    0    0    0    0    0    0  ...      0      0   
59996      3    0    0    0    0    0    0    0    0    0  ...      0      0   
59997      5    0    0    0    0    0    0    0    0    0  ...      0      0   
59998      6    0    0    0    0    0    0    0    0    0  ...      0      0   
59999      8    0    0    0    0    0    0    0    0    0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
59995      0      0      0      0      0      0      0      0  
59996      0      0      0      0      0      0      0      0  
59997      0      0      0      0      0      0      0      0  
59998      0      0      0      0      0      0      0      0  
59999      0      0      0      0      0      0      0      0  

[60000 rows x 785 columns]

In [4]:
X_train=np.array(df1)
X_train.shape

(60000, 785)

In [5]:
X_test=np.array(df2.loc[:,df2.columns!='label'])
Y_test=np.array(df2['label'])

In [6]:
len(X_test),len(Y_test)

(10000, 10000)

In [7]:
#classes
classes=[]
for i in range(10):
    classes.append(X_train[X_train[:,0] == i])
classes   

[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[2, 0, 0, ..., 0, 0, 0],
        [2, 0, 0, ..., 0, 0, 0],
        [2, 0, 0, ..., 0, 0, 0],
        ...,
        [2, 0, 0, ..., 0, 0, 0],
        [2, 0, 0, ..., 0, 0, 0],
        [2, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[3, 0, 0, ..., 0, 0, 0],
        [3, 0, 0, ..., 0, 0, 0],
        [3, 0, 0, ..., 0, 0, 0],
        ...,
        [3, 0, 0, ..., 0, 0, 0],
        [3, 0, 0, ..., 0, 0, 0],
        [3, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[4, 0, 0, ..., 0, 0, 0],
        [4, 0, 0, ..., 0, 0, 0],
        [4, 0, 0, ..., 0, 0, 0

In [10]:
#duplicate class  
class1 = []
for i in range(10):
    class1.append(X_train[X_train[:,0] == i])
class1[0]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [16]:
sum=0
for i in classes:
    print(len(i))
    sum+=len(i)
print(sum)

5923
6742
5958
6131
5842
5421
5918
6265
5851
5949
60000


In [12]:
sample1=[]
for i in range(10):
    for j in range(5):
        sample1.append(np.array(random.sample(list(class1[i]),int(len(class1[i])//5))))
        class1[i] = classes[i]
sample1

[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0

In [13]:
mean_dist={}
for i in range(len(classes)):
    mean_dist[f'{i}'] = np.mean(sample1[i][:,1:],axis=0)
mean_dist 

{'0': array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.08108108e-01,
        2.13682432e-01, 8.78378378e-02, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.0

In [14]:
mean_dist={}
for i in range(50):
    mean_dist[f'{i}']=np.mean(sample1[i][:,1:],axis=0)
mean_dist

{'0': array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.08108108e-01,
        2.13682432e-01, 8.78378378e-02, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.0

In [15]:
lst = []
for i in range(10):
    for j in range(5):
        lst.append(i)
np.array(lst)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8,
       8, 9, 9, 9, 9, 9])

In [16]:

Y_pred = []
for i in range(10000):
    
    distance = []
    index = 0
    Y = []
    for j in range(10):
        for k in range(5):
            distance.append(np.linalg.norm(X_test[i] - mean_dist[f'{index}']))
            index += 1
    distance = np.array(distance)
    distance = np.stack((distance,lst),axis = 1)
    distance = distance.astype("int64")
    distance = distance[distance[:,0].argsort()]
    Y = distance[:5]
    Y
    var = 0
    
    for j in range(5):
        for n in Y[:,1]:
            if np.count_nonzero(Y[:,1]== n) > 1:
                var = n
            else:
                var = n
    Y_pred.append(n)

In [17]:
Y_pred

[7,
 2,
 1,
 0,
 4,
 1,
 4,
 9,
 2,
 9,
 0,
 6,
 9,
 0,
 1,
 3,
 4,
 7,
 3,
 4,
 9,
 6,
 4,
 5,
 4,
 0,
 7,
 4,
 0,
 1,
 3,
 1,
 3,
 6,
 7,
 2,
 7,
 1,
 3,
 1,
 1,
 7,
 4,
 1,
 3,
 5,
 5,
 2,
 4,
 4,
 6,
 3,
 5,
 5,
 2,
 5,
 4,
 1,
 9,
 1,
 7,
 8,
 9,
 2,
 7,
 9,
 2,
 4,
 3,
 0,
 7,
 0,
 2,
 8,
 1,
 7,
 3,
 7,
 1,
 7,
 9,
 6,
 2,
 7,
 8,
 4,
 7,
 3,
 6,
 1,
 3,
 6,
 9,
 3,
 1,
 4,
 1,
 1,
 6,
 9,
 6,
 0,
 5,
 4,
 4,
 9,
 2,
 1,
 9,
 4,
 8,
 1,
 3,
 9,
 7,
 9,
 9,
 4,
 9,
 2,
 3,
 6,
 7,
 6,
 7,
 9,
 0,
 5,
 8,
 5,
 6,
 6,
 5,
 7,
 8,
 1,
 0,
 1,
 6,
 4,
 6,
 7,
 3,
 1,
 9,
 1,
 8,
 2,
 0,
 1,
 9,
 9,
 5,
 5,
 1,
 5,
 6,
 0,
 3,
 9,
 4,
 6,
 5,
 4,
 6,
 3,
 4,
 5,
 1,
 9,
 4,
 2,
 3,
 3,
 2,
 1,
 1,
 8,
 1,
 8,
 1,
 8,
 5,
 0,
 3,
 9,
 3,
 3,
 0,
 1,
 1,
 1,
 0,
 9,
 0,
 5,
 1,
 6,
 4,
 2,
 3,
 6,
 1,
 1,
 1,
 3,
 9,
 5,
 2,
 9,
 4,
 5,
 4,
 1,
 9,
 0,
 3,
 5,
 7,
 5,
 7,
 2,
 2,
 7,
 1,
 2,
 8,
 4,
 1,
 7,
 3,
 3,
 8,
 7,
 7,
 9,
 2,
 2,
 4,
 1,
 3,
 3,
 8,
 4,
 1,
 6,
 0,
 6,
 4,
 1,


In [18]:
count=0
for i in range(10000):
    if Y_pred[i]==Y_test[i]:
        count+=1
count

8111

In [19]:
Total_accuracy= count/len(Y_test)*100
print("total accuracy: ",Total_accuracy,'%')

total accuracy:  81.11 %


In [20]:
#class_wise comparision
compare=np.stack((Y_pred,Y_test),axis = 1)
compare

array([[7, 7],
       [2, 2],
       [1, 1],
       ...,
       [9, 4],
       [8, 5],
       [6, 6]], dtype=int64)

In [21]:
f_count=[]
for i in range(len(compare)):
    if compare[i,0] != compare[i,1]:
        f_count.append(Y_test[i])
    
len(f_count)
    

1889

In [22]:
for i in set(Y_pred):
    count_=list(Y_test).count(i)
    freq=f_count.count(i)
    print(f'Accuracy for class{i}:',100-freq/count_*100 )

Accuracy for class0: 88.46938775510205
Accuracy for class1: 95.77092511013215
Accuracy for class2: 73.83720930232558
Accuracy for class3: 80.79207920792079
Accuracy for class4: 80.5498981670061
Accuracy for class5: 66.14349775784754
Accuracy for class6: 86.01252609603341
Accuracy for class7: 82.58754863813229
Accuracy for class8: 73.30595482546201
Accuracy for class9: 80.37661050545094
